#define cwrite           YG_UTIL1_cwrite
#define cw_ecrire        YG_UTIL1_cw_ecrire
#define cread            YG_UTIL1_cread
#define date             YG_UTIL1_date
#define heure            YG_UTIL1_heure
#define index            YG_UTIL1_index
#define cherche          YG_UTIL1_cherche
#define trim_gauche      YG_UTIL1_trim_gauche
#define trim_droite      YG_UTIL1_trim_droite
#define trim             YG_UTIL1_trim
#define bina             YG_UTIL1_bina
#define hexa             YG_UTIL1_hexa
#define initanachai	 YG_UTIL1_initanachai
#define anachai		 YG_UTIL1_anachai
#define encadre		 YG_UTIL1_encadre
#define decadre		 YG_UTIL1_decadre
#define decadrep	 YG_UTIL1_decadrep
#define nfsuivant	 YG_UTIL1_nfsuivant
#define iabrev		 YG_UTIL1_iabrev
#define indice		 YG_UTIL1_indice
#define conversionl	 YG_UTIL1_conversionl
#define conversiond	 YG_UTIL1_conversiond
#define inicarsuiv	 YG_UTIL1_inicarsuiv
#define carsuiv		 YG_UTIL1_carsuiv
#define carsuiv_ligne	 YG_UTIL1_carsuiv_ligne
#define carsuiv_tamp	 YG_UTIL1_carsuiv_tamp
#define lecchaine	 YG_UTIL1_lecchaine
#define entrer_e	 YG_UTIL1_entrer_e
#define entrer_r	 YG_UTIL1_entrer_r
#define version_util	 YG_UTIL1_version

