#!/bin/bash
# v1.01

PCMCIA_DIR=/etc/pcmcia
MODULE=cei_pcc1553_cs

if test `ls /var/run | grep -c "cardmgr.pid"` -eq 0
  then	
    echo cardmgr not running.
    exit 1
fi

# send (SIGHUP) signal to 'cardmgr' to reload client database
PID=`cat /var/run/cardmgr.pid`
kill -s 1 ${PID}

# eject and than insert all cards in PCMCIA sockets
if test `/sbin/cardctl ident | grep -c "cei"` -gt 0
  then
    /sbin/cardctl eject
    /sbin/cardctl insert
fi

exit 0
