PACKAGE_NAME="ethercat"
PACKAGE_VERSION="1.6.8"
BUILT_MODULE_NAME[0]="ec_master"
BUILT_MODULE_LOCATION[0]="master"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/ethercat"
BUILT_MODULE_NAME[1]="ec_generic"
BUILT_MODULE_LOCATION[1]="devices"
DEST_MODULE_LOCATION[1]="/kernel/drivers/net/ethercat"
BUILT_MODULE_NAME[2]="ec_mini"
BUILT_MODULE_LOCATION[2]="examples/mini"
DEST_MODULE_LOCATION[2]="/kernel/drivers/net/ethercat"
AUTOINSTALL="yes"
MAKE[0]="./bootstrap && ./configure --enable-generic=yes --enable-8139too=no && make modules"
CLEAN="make clean"
