#!/bin/bash
#
# pcie6509      Startup script for the pcie6509
#
# chkconfig: 
# description: 


. /etc/rc.d/init.d/functions
. /etc/drast_lkm/pcie6509.conf

DEVICE=pcie6509

start() {
	modprobe ${DEVICE} $MODARGS
	
	if [ "$MODARGS" = "" ]
	then
		MODARGS="tf1=0 tf2=0 tf3=0 tf4=0"
	fi
	MAJOR=`fgrep pcie6509 /proc/devices | cut -f 1 -d ' '` 
	if  [ "$MAJOR" = "" ]
	then
		return 1
	fi 
	rm -rf /dev/${DEVICE}*
	for fifo in 0 1 2 3
	do
		MINOR=`echo $fifo | cut -f 1 -d '=' | cut -f 2 -d 'f'`
		mknod /dev/${DEVICE}$MINOR c $MAJOR $MINOR
		chmod 666 /dev/${DEVICE}$MINOR
		if [ "$DEVGROUP" != "" ]
		then
			chgrp $DEVGROUP /dev/${DEVICE}$MINOR
		fi
	done
	return 0
}

stop() {
	rmmod ${DEVICE} && rm -rf /dev/${DEVICE}* || echo "pcie6509 not unloaded. Was not loaded or can't unload. Check all using modules are unloaded."
}

show_status() {
	fgrep pcie6509 /proc/devices && echo "pcie6509 is loaded" || echo "no pcie6509 loaded"
}


case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		start
		stop
		;;
	status)
		show_status
		;;
esac
