/**
 * @file Enumerator.hpp
 * @brief Class for discovering and configuring EtherCAT slaves on the network.
 */

#pragma once

#include "resoem/RawSocket.hpp"
#include "resoem/Slave.hpp"
#include "resoem/common.hpp"
#include "resoem/soem_eni.hpp"
#include <chrono>
#include <span>
#include <string>
#include <vector>

namespace resoem {

class ProcessImage;

/**
 * @brief Manages the discovery, initialization, and monitoring of EtherCAT
 * slaves.
 *
 * The Enumerator is responsible for scanning the network, assigning station
 * addresses, reading slave information (SII), and handling state transitions.
 */
class Enumerator {
public:
  /**
   * @brief Construct a new Enumerator.
   * @param socket The raw socket to use for communication.
   */
  Enumerator(RawSocket &socket);

  /**
   * @brief Run the full enumeration process.
   *
   * This includes resetting the network, counting slaves, assigning addresses,
   * and reading device information from the SII (EEPROM).
   *
   * @return Result<size_t> Number of slaves found or an error code.
   */
  Result<size_t> enumerate();

  /**
   * @brief Request a state transition for a specific slave.
   *
   * @param slave_idx Index of the slave in the internal list.
   * @param state Target AL state (e.g., states::PRE_OP).
   * @param timeout Maximum time to wait for the transition.
   * @return Result<uint16_t> The actual state reached or an error.
   */
  Result<uint16_t>
  request_state(uint16_t slave_idx, uint16_t state,
                std::chrono::microseconds timeout = std::chrono::seconds(3));

  /**
   * @brief Request a state transition for ALL slaves simultaneously.
   *
   * @param state Target AL state.
   * @param timeout Maximum time to wait for all slaves to transition.
   * @return Result<> Success or error.
   */
  Result<> request_state_all(uint16_t state, std::chrono::microseconds timeout =
                                                 std::chrono::seconds(3));

  /**
   * @brief Configure FMMUs (Fieldbus Memory Management Units) for process data.
   *
   * Maps slave physical memory (PDOs) to the logical process image.
   *
   * @param image The process image to configure.
   * @return Result<uint32_t> Total logical size in bytes.
   */
  Result<uint32_t> configure_fmmu(ProcessImage &image);

  /**
   * @brief Exchange process data using a Logical ReadWrite (LRW) command.
   *
   * @param image The process image containing outputs to send and buffer for
   * inputs.
   * @param timeout Receive timeout.
   * @return Result<uint16_t> Working Counter (WKC) from the datagram.
   */
  Result<uint16_t> exchange_process_data(
      ProcessImage &image,
      std::chrono::microseconds timeout = std::chrono::milliseconds(2));

  /**
   * @brief Read a 32-bit word from the slave's SII (EEPROM).
   *
   * @param slave_idx Index of the slave.
   * @param word_addr Word address in the EEPROM.
   * @return uint32_t The value read or 0xFFFFFFFF on failure.
   */
  uint32_t read_eeprom(uint16_t slave_idx, uint16_t word_addr);

  /**
   * @brief Write a 16-bit word to the slave's SII (EEPROM).
   *
   * @param slave_idx Index of the slave.
   * @param word_addr Word address in the EEPROM.
   * @param data The 16-bit data to write.
   * @return int 1 on success, 0 on failure.
   */
  int write_eeprom(uint16_t slave_idx, uint16_t word_addr, uint16_t data);

  /**
   * @brief Load configuration from an ENI structure.
   *
   * Applies CoE initialization commands from the ENI to the discovered
   * slaves.
   *
   * @param eni Pointer to the ENI structure (generated by eniconv).
   */
  void load_eni(const ec_enit *eni);

  /**
   * @brief Measure propagation delays between slaves for Distributed Clocks
   * (DC).
   */
  void measure_propagation_delays();

  /**
   * @brief Synchronize all slave clocks to the Reference Clock (usually the
   * first DC-capable slave).
   */
  void sync_clocks();

  /**
   * @brief Configure SYNC0/SYNC1 signals for a specific slave.
   *
   * @param slave The slave info structure.
   * @param cycle_time Sync cycle time in nanoseconds.
   * @param shift_time Sync shift time in nanoseconds.
   */
  void configure_dc(SlaveInfo &slave, uint32_t cycle_time, int32_t shift_time);

  /**
   * @brief Check status of all slaves and update 'online' and
   * 'current_state' fields.
   */
  void check_slaves_status();

  /**
   * @brief Attempt to recover a slave that has gone offline or errored.
   *
   * @param slave_idx Index of the slave.
   * @return true if recovery was successful.
   */
  bool recover_slave(int slave_idx);

  /**
   * @brief Get the list of discovered slaves.
   * @return Constant reference to the slave list.
   */
  const std::vector<SlaveInfo> &slaves() const { return slaves_; }

private:
  RawSocket &socket_;             ///< Raw socket reference
  std::vector<SlaveInfo> slaves_; ///< List of discovered slaves
  uint8_t current_idx_ = 0;       ///< Cyclic index for datagrams

  // Internal helper methods
  int broadcast_read_count();
  void reset_to_init();
  void assign_addresses(int count);
  void read_sii_data(int count);
  void read_sii_categories(int slave_idx);
  void read_sii_pdos(int slave_idx);
  void map_topology(int count);

  int send_receive(uint8_t cmd, uint16_t addr, uint16_t offset,
                   std::span<byte> data);

  template <typename T> T read_register_broadcast(uint16_t reg, int &wkc);
  template <typename T>
  int write_register_broadcast(uint16_t reg, const T &value);
  template <typename T>
  T read_register_aprd(uint16_t auto_inc_addr, uint16_t reg, int &wkc);
  template <typename T>
  int write_register_apwr(uint16_t auto_inc_addr, uint16_t reg, const T &value);
  template <typename T>
  T read_register_fprd(uint16_t configured_addr, uint16_t reg, int &wkc);
  template <typename T>
  int write_register_fpwr(uint16_t configured_addr, uint16_t reg,
                          const T &value);

  uint32_t read_sii_word(uint16_t slave_cfg_addr, uint16_t word_addr);
  uint16_t find_sii_category(uint16_t slave_cfg_addr, uint16_t cat_type);
  void read_port_status();
  std::string read_sii_string(uint16_t slave_cfg_addr, uint8_t string_idx);
};

} // namespace resoem
