#!/bin/bash
#
# cevt      Startup script for the CEVT
#
# chkconfig: 2345 70 30
# description: CEVT is a linux kernel module to send thoer's module IO events
#              into common FIFO.


. /etc/rc.d/init.d/functions
. /etc/drast_lkm/cevt.conf

DEVICE=cevt

start() {
	modprobe ${DEVICE} $MODARGS
	
	if [ "$MODARGS" = "" ]
	then
		MODARGS="tf1=0 tf2=0 tf3=0 tf4=0"
	fi
	MAJOR=`fgrep CEVT /proc/devices | cut -f 1 -d ' '` 
	if  [ "$MAJOR" = "" ]
	then
		return 1
	fi 
	rm -rf /dev/${DEVICE}*
	for fifo in $MODARGS
	do
		MINOR=`echo $fifo | cut -f 1 -d '=' | cut -f 2 -d 'f'`
		mknod /dev/${DEVICE}$MINOR c $MAJOR $MINOR
		chmod 666 /dev/${DEVICE}$MINOR
		if [ "$DEVGROUP" != "" ]
		then
			chgrp $DEVGROUP /dev/${DEVICE}$MINOR
		fi
	done
	return 0
}

stop() {
	rmmod ${DEVICE} && rm -rf /dev/${DEVICE}* || echo "CEVT not unloaded. Was not loaded or can't unload. Check all using modules are unloaded."
}

show_status() {
	fgrep CEVT /proc/devices && echo "CEVT is loaded" || echo "no CEVT loaded"
}


case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		start
		stop
		;;
	status)
		show_status
		;;
esac
