#!/bin/bash
# v1.01


PCMCIA_DIR=/etc/pcmcia
MODULE=cei_pcc1553_cs

# eject all cards in PCMCIA sockets
if test `/sbin/cardctl ident | grep -ci "cei"` -gt 0
  then
    /sbin/cardctl eject
fi

if test `ps -ef | grep -ci "/sbin/cardmgr"` -ne 0
  then
    # send (HUP) signal to 'cardmgr' to reload client database
    PID=`ps -ef | grep -m 1 "/sbin/cardmgr" | awk '{print $2}'`
    kill -HUP ${PID}
fi

exit 0
