# Makefile for uceipci

all:
	$(MAKE) -C Condor_Engineering/Drivers/3.0/pci

clean:
	$(MAKE) -C Condor_Engineering/Drivers/3.0/pci clean

install:
	$(MAKE) -C Condor_Engineering/Drivers/3.0/pci install
