plugins:
- search
site_name: Quasar Documentation
theme:
  features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  name: material
  palette:
    accent: indigo
    primary: indigo
    scheme: slate
