#!/bin/bash
# v1.02


# path to binaries
PATH_RMMOD=/sbin/rmmod

MODULE=uceipci

if test `cat /proc/devices | grep -ci "${MODULE}"` -eq 0
  then
    echo Driver ${MODULE} is not loaded
    exit 1
fi

echo Removing driver ${MODULE}
${PATH_RMMOD} ${MODULE}.ko
#/sbin/modprobe -r ${MODULE}

if test `cat /proc/devices | grep -ci "${MODULE}"` -eq 0
  then
    echo Successfully removed ${MODULE} driver
  else
    echo Failed to remove ${MODULE} driver
fi

if test `ls /dev | grep -ci "${MODULE}_"` -ne 0
  then
    echo Removing nodes for ${MODULE}
    rm -f /dev/${MODULE}_[0-7]
fi

exit 0
