#!/bin/sh

###############################################################################
#                                                                             #
# File:         ai64_init                                                     #
#                                                                             #
# Description:  Init script                                                   #
#                                                                             #
# Date:         10/06/2008                                                    #
# History:                                                                    #
#                                                                             #
#   2  10/06/08  D. Dubash                                                    #
#                Support for chkconfig                                        #
#                                                                             #
#   1  03/21/07  D. Dubash                                                    #
#                Initial release                                              #
#                                                                             #
###############################################################################
#                                                                             #
#  Copyright (C) 2007 and beyond Concurrent Computer Corporation              #
#  All rights reserved                                                        #
#                                                                             #
###############################################################################

# chkconfig: 2345 50 50
# description: ai64 Driver

prog="ai64"
CONFIG_DIR=/usr/lib/config

# Source function library
if
  [ -f /etc/rc.d/init.d/functions ]
then
  . /etc/rc.d/init.d/functions
else
  function action {
    echo -n "$1... "
    shift
    $@
    stat=$?
    if [ $stat = 0 ]; then
      echo success
    else
      echo failure
    fi
    return  $stat
  }
fi

start() {
        cd /etc/init.d
        if sh ${CONFIG_DIR}/${prog}_start 
        then
            action "Starting $prog: " /bin/true
        else
            action "Starting $prog: " /bin/false
        fi
        return
}

stop() {
        cd /etc/init.d
        if sh ${CONFIG_DIR}/${prog}_start -x
        then
            action "Stopping $prog: " /bin/true
        else
            action "Stopping $prog: " /bin/false
        fi
        return
}

# See how we are called
case "$1" in

  start|load)
        start
        ;;

  stop|unload)
        stop
        ;;

  restart|reload)
        echo "=== Restarting ${prog} ==="
        stop
        start
        ;;

  status)
        /sbin/lsmod | /bin/grep -w ${prog} > /dev/null 2>&1
        RETVAL=$?
        if [ $RETVAL == 0 ]
        then
            echo ${prog}: module is loaded
        else
            echo ${prog}: module is not present
        fi
        ;;

  *)
        echo "Usage: ${prog} {start|load|stop|unload|restart|reload|status}"
        exit 1
esac

exit 0
