#!/bin/sh
# $URL: http://subversion:8080/svn/gsc/trunk/drivers/LINUX/OPTO16X16/OPTO16X16_Linux_1.x.x.x_GSC_DN/make_all $
# $Rev: 53731 $
# $Date: 2023-09-14 10:49:58 -0500 (Thu, 14 Sep 2023) $

# OPTO16X16: Overall make script



#==============================================================================
_process_sources() {
	# 1 = name of "sources" script to process
	# 2 = build target

	SRC=${1}
	DST=_sources

	if [ -e ${SRC} ]
	then
		# The above named file is present at GSC for development purposes only
		# and is not distributed in driver archives.

		D2U=`which dos2unix 2>/dev/null | wc -l`

		if [ "${D2U}" != "1" ]
		then

			D2U=~/c/gsc/gsc_common/utils/linux/d2u

		else

			D2U=dos2unix

		fi

		rm -f ${DST}

		chmod +w ${SRC}
		${D2U} ${SRC}	 2>/dev/null  1>/dev/null
		chmod +x ${SRC}
		${SRC}

		make -f ${DST} ${2}

		rm -f ${DST}

	fi
}



#==============================================================================
_process() {
	# 1 = directory name
	# 2 = build target

	if [ -d ./${1} ]
	then

		echo -e "======================================================================\r${1} "

		CWD=`pwd`

		cd ./${1}

		_process_sources ./sources ${2}

		if [ -e ./makefile ]
		then

			make -f ./makefile ${2}

		elif [ -e ./Makefile ]
		then

			make -f ./Makefile ${2}

		fi

		cd ${CWD}

	fi
}



#==============================================================================

_process driver						${1}

if [ ! "${1}" != "" ]
then
./driver/start
fi

_process include					${1}
_process api						${1}
_process docsrc						${1}
_process utils						${1}
_process lib						${1}

_process samples/din				${1}
_process samples/dout				${1}
_process samples/id					${1}
_process samples/regs				${1}
_process samples/sbtest				${1}
_process samples/tftest				${1}

if [ -d ./samples/metrics ]
then
echo -n
_process ./samples/metrics			${1}
fi

