#!/bin/bash

### BEGIN INIT INFO
# Provides:          opto16x16
# Required-Start:    
# Required-Stop:     
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Startup script for the opto16x16 IO device
# Description:       Startup script for the opto16x16 IO device
### END INIT INFO

# opto16x16    Startup script for the opto16x16 IO device
#
# chkconfig: 2345 80 20
# description: opto16x16 is a 16 digital inputs, 16 digital output 
#	       optoisolated board.

if [ -f /etc/rc.d/init.d/functions ]; then
	. /etc/rc.d/init.d/functions
fi
. /etc/drast_lkm/opto16x16.conf

start() {
	modprobe opto16x16
	MAJOR=`fgrep opto16x16 /proc/devices | cut -f 1 -d ' '` 
	if  [ "$MAJOR" = "" ]
	then
		return 1
	fi 
	rm -rf /dev/opto16x16*
	count=`grep "^boards: [0-9]*$" /proc/opto16x16 | cut -d " " -f 2`
	i=0
	while [ $i -lt $count ]
	do
		mknod /dev/opto16x16$i c $MAJOR $i
		chmod 660 /dev/opto16x16$i
		if [ "$DEVGROUP" != "" ]
		then
			chgrp $DEVGROUP /dev/opto16x16$i
		fi
		i=`expr $i + 1`
	done
	return 0
}

stop() {
	rmmod opto16x16 && rm -rf /dev/opto16x16* || echo "opto16x16 not unloaded. Was not loaded or can't unload. Check all user modules are unloaded."
}

show_status() {
	fgrep opto16x16 /proc/devices && cat /proc/opto16x16 || echo "no opto16x16 loaded."
}


case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		show_status
		;;
esac
