#!/bin/bash
#
# pmc424    Startup script for the pmc424 IO device
#
# description: pmc424 is a TTL IO board of acromag


. /etc/drast_lkm/apmc424.conf

start() {
	/sbin/modprobe apmc424
	MAJOR=`fgrep apmc424 /proc/devices | cut -f 2 -d ' '` 
	mknod /dev/apmc424_0 c $MAJOR 0
	chmod 660 /dev/apmc424_0
	if [ "$DEVGROUP" != "" ]
	then
		chgrp $DEVGROUP /dev/apmc424_0
	fi
	return 0
}

stop() {
	rmmod apmc424 && rm -rf /dev/apmc424* || echo "apmc424 not unloaded. Was not loaded or can't unload. Check all user modules are unloaded."
}

show_status() {
	fgrep apmc424 /proc/devices || echo "no apm424 loaded."
}


case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restar)
		start
		stop
		;;
	status)
		show_status
		;;
esac

